//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWorksSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Descipline { get; set; }
        public string Hashtags { get; set; }
        public Nullable<double> Plagiarism { get; set; }
        public int Documet { get; set; }
        public string Authors { get; set; }
        public string Uploader { get; set; }
        public string University { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Files Files { get; set; }
        public virtual University University1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
